url: "" # the base hostname & protocol for your site
baseurl: "alistaircook.com/" # the subpath of your site, e.g. /blog/

title: Alistair Cook
subtitle: Improv performer and teacher
description: Alistair Cook is an improviser from Vancouver, Canada who, over the past 25 years, has had the great opportunity to work with improvisers both young and old, perform and instruct at festivals, and consult and direct for theatre companies across Europe, the USA, Australia, and Canada.

exclude: ["_assets", "gulp", ".gitignore", "gulpfile.js", "package.json", "node_modules", "README.md"]
keep_files: ["assets"]
